// Start the Pipeline
pipeline {
  // Define the agent where it will run
  agent {
    // kubernetes = kubernetes cloud in Jenkins
    kubernetes { 
// Define the pod template, what will the pods be, and resources for them
// Pass the 'dockercred' (stored in Kubernetes) as the secret that Kaniko needs to push to Docker Hub
yaml '''
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - 1d
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    projected:
      sources:
      - secret:
          name: dockercred
          items:
          - key: .dockerconfigjson
            path: config.json
'''
    }
  }
// Start declaring the stages of the pipeline
  stages { 
    // Stage #1 - Clone the repository
    stage('Clone Repository to Kaniko') {
      steps {
        container('kaniko') {
          git url: 'https://github.com/PREngineer/prengineer.github.io', branch: 'master'
        }
      }
    }
    // Stage #2 - Build the Docker image using Kaniko and push to registry
    stage('Build and Push Docker Image to Registry') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor --context "`pwd`" --destination prengineer/cvjp:latest
          '''
        }
      }
    }
    // Stage #3 - Remove previous pods
    stage('Delete previous pods for redeployment by ArgoCD') {
      steps {
        sshagent(credentials: ['k3s']) {
          sh '''
            ssh -o StrictHostKeyChecking=no -l jorge.l.pabon.cruz pi1 kubectl delete pods --all --namespace=cvjp
          '''
        }
      }
    }
  }
}